version: '3'
services:
  databrary-base:
    build: 
      context: ./databrary/
      dockerfile: Dockerfile_base
    image: databrary-base


  postgres:
    build: ./postgres/
    image: databrary_postgres
    ports:
      - "5432:5432"

  solr:
    image: solr
    ports:
      - "8983:8983"
networks:
  default:
    external:
      name: databrary
