version: '3'
services:
  databrary: 
    build: 
      context: ./databrary/
      dockerfile: Dockerfile_final
    image: databrary_databrary:final
    depends_on:
      - postgres
      - solr
    volumes:
      - ./databrary/databrary_config:/tmp/databrary_config
    ports: 
      - "8642:8642"
    links:
      - "postgres:databrary_postgres"
      - "solr:databrary_solr"
    command: stack exec databrary -- -c /tmp/databrary_config/databrary.conf

  postgres:
    build: ./postgres/
    image: databrary_postgres
    volumes_from:
      - databrary_dbstore
    ports:
      - "5432:5432"
  
  databrary_dbstore:
    image: databrary_dbstore
    volumes: /var/lib/postgresql/data  

  solr:
    image: solr
    ports:
      - "8983:8983"

