version: '2'
services:
  databrary: 
    build: 
      context: ./databrary/
      dockerfile: Dockerfile_final
    image: databrary_databrary:final
    depends_on:
      - databrary_postgres
      - databrary_solr
    volumes:
      - ./databrary/databrary_config/databrary.conf:/home/databrary/src/databrary.conf
      - databrary_logs_store:/databrary_logs
      - /nyu:/nyu
    ports: 
      - "8642:8642"
    links:
      - "databrary_postgres:databrary_postgres"
      - "databrary_solr:databrary_solr"

  databrary_postgres:
    build: ./postgres/
    image: databrary_postgres
    volumes:
      - databrary_postgres_store:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  databrary_solr:
    build: ./solr
    image: databrary_solr
    ports:
      - "8983:8983"
    volumes:
      - databrary_solr_store:/opt/solr

volumes:
  databrary_solr_store:
    external: true
  databrary_postgres_store:
    external: true
  databrary_logs_store:
    external: true
